### PR TITLE
fix hideDeletion bug, fixed file header

### PR DESCRIPTION
**Pull request by GingerBear**
@MuscularMustache 

fix hideDeletion bug that keep adding `+`. Problem is when file doesn't have line deleted, it was think deleted line be restored, so try to add `+` back.

Also add a feature that set file header position fixed to top. This is useful we viewing long files, we don't need to scroll to top to click the buttons we added.

@johnhof plan to add this to JiraJockey?

### CODE REVIEW

**Comment by johnhof** [comment]
@GingerBear I'm always up for expanding it. I dont want to bogart someone else's work though

**Comment by GingerBear** [comment]
@johnhof oh, yeah, after urban dic for a while what "bogart" mean, feel you guys just so careful about these "ethic concern", and feel myself like a uncivilized person. :smile:

**Comment by johnhof** [comment]
hahaha, after I posted that I googled it to make sure there was a reasonable definition in the results. 

But I'd steal it if it wasnt written by someone I know. Very little ethical concern when it comes to reusing code haha

**Comment by MuscularMustache** [comment]
:+1: It looks good. So im going to pull the ole trust merge maneuver. Haha

**Comment by MuscularMustache** [comment]
Also @GingerBear Thanks for removing lodash. I forgot i left it in there when i was trying to use decodeCleanText

**Pull request merged**
